
[webservers]


web-1   ansible_host=89.169.159.246 fqdn=fhmrgrgb5sc2034h132f.auto.internal

web-2   ansible_host=51.250.14.125 fqdn=fhm3difjbkb8ecgbq5c6.auto.internal






[databases]

main   ansible_host=89.169.129.79 fqdn=fhm8ahku1a9gv6k68350.auto.internal

replica   ansible_host=89.169.140.51 fqdn=fhmqna140e4cjdl6jpcd.auto.internal



[storage]


storage   ansible_host=89.169.140.81 fqdn=fhm9s27fdsq2vael41iq.auto.internal


